config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"
  
  root to: 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/profile', to:'static_pages#profile'
  match '/newrequest', to:'static_pages#newrequest'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def newrequest
  end
  
  def profile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Life Buoy"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<button class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	
	
			<%= link_to "Life Buoy", root_path, id: "logo" %>
			
			<div class="nav-collapse collapse">
				<ul class="nav pull-right" style="float:right;">
					<li><%= link_to "Profile", profile_path%> </li>
					<li><%= link_to "Home", root_path%> </li>
					<li><%= link_to "Medications", help_path%> </li>
					<li><%= link_to "Around Me", signup_path%> </li>
					<li><%= link_to "Physicians",   about_path %></li>
				</ul>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
  	<title><%= full_title(yield(:title)) %></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
	<link href="http://twitter.github.io/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
  <style>
    body {
      padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
    }
  </style>
  <link href="http://twitter.github.io/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
  
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>

	<%= render 'layouts/header' %>
	
	<div class="container-fluid">
		
		<%= yield %>
		
		<!-- <%= render 'layouts/footer' %> ->
	</div>


	
		
</body>
</html>

app/views/static_pages/about.html.erb
<div class="center">
	<!--
	<ul class="nav pull-left" style="float:left;">
		<li><h3>Dr. Peggy Bui</h3> </li>
		<li><h3>Dr. Peggy Bui</h3> </li>
		<li><h3>Dr. Peggy Bui</h3> </li>
		<li><h3>Dr. Peggy Bui</h3> </li>
	</ul>
	-->
	<table RULES=ROWS FRAME=HSIDES style="width: 100%; margin:auto;">
	<tr>
	<td align="left"><%= image_tag("peg-circ@100.png", alt: "Peggy")%></td>
	<td align="right"><h3>Dr. Peggy Bui</h3> </td>
	</tr>
	
	<tr>
	<td align="left"><%= image_tag("joe-circ@100.png", alt: "Peggy")%></td>
	<td align="right"><h3>Dr. Joe Hanson</h3> </td>
	</tr>
	
	<tr>
	<td align="left"><%= image_tag("jacob-circ@100.png", alt: "Peggy")%></td>
	<td align="right"><h3>Dr. Jacob Heller</h3> </td>
	</tr>
	
	<tr>
	<td align="left"><%= image_tag("lita-circ@100.png", alt: "Peggy")%></td>
	<td align="right"><h3>Dr. Lita Patel</h3> </td>
	</tr>
	</table>
</div>
<!--	
	<table>
		<tr> 
			<td align="left" style="width:185px;height:239px"><%= image_tag("matt-circ.png", alt: "Matthew")%> </td>
			<td style="overflow:hidden;max-width:810px"><p><b>Matthew Chan</b> is a 2nd year Ph.D. candidate in Informatics at the University of California, Irvine, and he is a member of the Laboratory for Ubiquitous Computing and Information (LUCI). He graduated from the University of California, Berkeley studying Computer Science, with a focus on Human-Computer Interaction, and performed researched on education and health care at The Berkeley Institute of Design. Mr. Chan previously worked on iOS development at Twitter and Cisco.</p></td>
		</tr>
		<tr> 
			<td align="left" style="width:185px;height:239px"><%= image_tag("peg-circ.png", alt: "Peggy")%> </td>
			<td style="overflow:hidden;max-width:810px"><p><b>Peggy Bui</b> is an MD/MBA candidate at the University of California, Irvine, focusing on healthcare innovations and technology. She graduated with honors from Harvard College and worked in strategy consulting at Monitor Group prior to pursuing graduate school. At Monitor, she advised Fortune 500 companies on strategic business capabilities, including: analyzing the future of the healthcare space for a health insurance company, and reassessing the product line of a global telecommunications firm. 
				</p></td>
		</tr>
		
		<tr> 
			<td align="left" style="width:185px;height:239px"><%= image_tag("bryan-circ.png", alt: "Bryan")%> </td>
			<td style="overflow:hidden;max-width:810px"><p><b>Bryan Lam</b> is currently a 2nd year student at the University of California, Irvine, where he is studying to obtain his Bachelor’s of Science in Computer Science. He is currently working as an iOS development intern at Teradek.
				</p></td>
		</tr>

		
		<tr> 
			<td align="left" style="width:185px;height:239px"><%= image_tag("lita-circ.png", alt: "Lita")%> </td>
			<td style="overflow:hidden;max-width:810px"><p><b>Lita Patel</b> is currently a 4th year student at the University of California, Irvine, where she expects to obtain her Bachelor’s of Science in Business Information Management. Previously, she worked as a business intern at California Stem, Inc. where she worked under the General Manager and COO of the company.
				</p></td>
		</tr>
		
		<tr> 
			<td align="left" style="width:185px;height:239px"><%= image_tag("joe-circ.png", alt: "Joseph")%> </td>
			<td style="overflow:hidden;max-width:810px"><p><b>Joseph Hanson</b> is an MD/MBA candidate at the University of California, Irvine. He graduated from Johns Hopkins University with a B.A. in Neuroscience, Chemistry, Mathematics, and English. He has worked as a research coordinator at the Kennedy Krieger Institute in Baltimore, MD. He is currently performing neuro-oncology research in the Chao Family Cancer Center at UC Irvine.
				</p></td>
		</tr>
		
		<tr> 
			<td align="left" style="width:185px;height:239px"><%= image_tag("jacob-circ.png", alt: "Jacob")%> </td>
			<td style="overflow:hidden;max-width:810px"><p><b>Jacob Heller</b> is pursuing an M.S. in Computer Science at the University of California, Irvine. He obtained his B.A. in Computer Science from Claremont McKenna College and has focused his career on the development and application of artificially intelligent systems. He is the lead tech developer for www.thewelcomingcommittee.com.
				</p></td>
		</tr>
	</table>

	<table width="100%">
		<tr> 
			<td align="center" style="overflow:auto; height:200px;"><%= image_tag("matt-circ.png", alt: "Matthew")%> </td>
			<td align="center" style="overflow:auto; height:200px;"><%= image_tag("peg-circ.png", alt: "Peggy") %> </td>
			<td align="center" style="overflow:auto; height:200px;"><%= image_tag("bryan-circ.png", alt: "Bryan") %> </td>
		</tr>
		<tr> 
			<td align="center">Matthew K. Chan </td>
			<td align="center">Peggy Bui</td>
			<td align="center">Bryan Lam</td>
		</tr>
	</table>
	
	</br>
	<table width="100%">
		<tr> 
			<td style="overflow:auto; height:200px;" align="center"><%= image_tag("lita-circ.png", alt: "Lita") %> </td>
			<td style="overflow:auto; height:200px;" align="center"><%= image_tag("joe-circ.png", alt: "Joseph") %> </td>
			<td style="overflow:auto; height:200px;" align="center"><%= image_tag("jacob-circ.png", alt: "Jacob") %> </td>
		</tr>
		<tr> 
			<td align="center">Lita Patel </td>
			<td align="center">Joseph Hanson </td>
			<td align="center">Jacob Heller</td>
		</tr>
	</table>
</div>

-->

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Life Buoy at the
  <a href="#">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Medications</h1>
	<p>
		Get help on the Ruby on Rails Tutorial at the
		  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
		  To get help on this sample app, see the
		  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
	</p>
 

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<h1>Life Buoy</h1>
<h2>Telemedicine @ Your Fingertips</h2>

	<p>
		Life Buoy is an innovative iOS and Web application that wirelessly connects patients to physicians. Its purpose is three-fold: to provide non-emergent medical consults, to reach patients in rural and underserved regions, and to help train the next generation’s tech-savvy physicians. By leveraging a user-friendly interface on popular smartphone and tablet platforms, Life Buoy is able to provide instantaneous video consultations with physicians over any geographical distance, up-to-date GPS locations of relief centers and emergency rooms, and instantaneous e-prescription of vital medicines to nearby pharmacies. 
	</p>
	<%= link_to image_tag("buttonAdd@2x.png", alt: "New Request"), newrequest_path %>
</div>

app/views/static_pages/newrequest.html.erb
<% provide(:title, 'New Request') %>
<h1>New Request</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/profile.html.erb
<% provide(:title, 'Profile') %>
<%= image_tag("matt-bkg@2x.png", alt: "Matthew")%>

<h2 style="background-color:#ff7300;color:white;">Allergies</h2>
<%= image_tag("allergiesView@2x.png", alt: "Allergies")%>

<h2 style="background-color:#ff7300;color:white;">Surgical History</h2>
<%= image_tag("surgicalView@2x.png", alt: "Surgery")%>

<h2 style="background-color:#ff7300;color:white;">Contact</h2>
<%= image_tag("contactsView@2x.png", alt: "Contacts")%>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>